export { classify } from './classifier/classifier';
export type { ClassifyInput, ClassificationResult } from './classifier/classifier';
export { scoreCategories } from './classifier/scorer';
export type { CategoryScore } from './classifier/scorer';
export { KEYWORD_DICTIONARY } from './dictionaries/keywords';
export { SYNONYM_DICTIONARY } from './dictionaries/synonyms';
export { INSTITUTION_CATEGORY_MAP } from './dictionaries/institutions';
export { ACTION_KEYWORDS } from './dictionaries/actions';
export type { ActionType } from './dictionaries/actions';
export { CATEGORIES } from './data/categories';
